# Generated by Django 6.0.6 on 2026-06-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('name', models.CharField(help_text='e.g., 25th Batch, Spring 2026', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (Currently Studying)'), ('GRADUATED', 'Graduated / Alumni (Archived)')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('credits', models.IntegerField()),
                ('student_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sunday, Monday', max_length=15, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Student capacity of this room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Theory, Lab', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_data', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_routine_locked', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_lunch_break', models.BooleanField(default=False, help_text='Global lunch break flag.')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTimeConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('constraint_type', models.CharField(choices=[('CLASS_OFF', 'Class Off / Blocked'), ('FORCE_ALLOW_LUNCH_CLASS', 'Force Allow Class During Lunch')], default='CLASS_OFF', max_length=50)),
                ('batch', models.ForeignKey(blank=True, help_text='Optional: Apply only to a specific batch', null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.batch')),
            ],
        ),
    ]
