# Generated by Django 6.0.6 on 2026-06-17 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.day'),
        ),
        migrations.AddField(
            model_name='batchtimeconstraint',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.day'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_courses', to='academic.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='offering_department',
            field=models.ForeignKey(blank=True, help_text='Who teaches this? Leave blank if same as Target Department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_courses', to='academic.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_room_department',
            field=models.ForeignKey(blank=True, help_text='Force algorithm to look for rooms in this specific department first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_room_courses', to='academic.department'),
        ),
        migrations.AddField(
            model_name='batchtimeconstraint',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academic.department'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.roomsubtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.roomsubtype'),
        ),
        migrations.AddField(
            model_name='roomsubtype',
            name='main_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='academic.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.roomtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.roomtype'),
        ),
        migrations.AddField(
            model_name='routinebackup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department'),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.day'),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.room'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester'),
        ),
        migrations.AddField(
            model_name='batchtimeconstraint',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester'),
        ),
        migrations.AddField(
            model_name='batch',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.semester'),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.timeslot'),
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.timeslot'),
        ),
        migrations.AddField(
            model_name='batchtimeconstraint',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='routineentry',
            unique_together={('day', 'time_slot', 'course'), ('day', 'time_slot', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='batchtimeconstraint',
            unique_together={('department', 'semester', 'batch', 'day', 'time_slot')},
        ),
    ]
