# Generated by Django 5.2.8 on 2026-06-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='room_number',
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], help_text='অ্যাডমিন চাইলে নির্দিষ্ট দিন ফিক্সড করতে পারে', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_time_slot',
            field=models.ForeignKey(blank=True, help_text='অ্যাডমিন চাইলে নির্দিষ্ট টাইম স্লট ফিক্সড করতে পারে', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.timeslot'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='এই কোর্সে মোট ছাত্র সংখ্যা'),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.CharField(blank=True, help_text='ল্যাব হলে স্পেসিফিক ক্যাটাগরি (যেমন: Computer Lab)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='এই রুমের ছাত্র ধারণক্ষমতা')),
                ('room_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10)),
                ('sub_category', models.CharField(blank=True, help_text='যেমন: Computer Lab, Electronics Lab (ঐচ্ছিক)', max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.department')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routineentry',
            unique_together={('day', 'time_slot', 'course')},
        ),
        migrations.AddField(
            model_name='course',
            name='fixed_room',
            field=models.ForeignKey(blank=True, help_text='অ্যাডমিন চাইলে এই কোর্সের জন্য নির্দিষ্ট রুম ফিক্সড করতে পারে', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.room'),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.room'),
        ),
        migrations.AlterUniqueTogether(
            name='routineentry',
            unique_together={('day', 'time_slot', 'course'), ('day', 'time_slot', 'room')},
        ),
    ]
